// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg9b9DBACCHumnRCgwJvOmS8FaRbZauQ',
    authDomain: 'cbt-lpk.firebaseapp.com',
    projectId: 'cbt-lpk',
    storageBucket: 'cbt-lpk.appspot.com',
    messagingSenderId: '1041673028858',
    appId: '1:1041673028858:web:22357933f2b6bbfe19f543',
    measurementId: 'G-L7HVKKQD8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOlF17rro_u1DMBiQgxHpNtqiZEg3NlbY',
    appId: '1:1041673028858:android:1c3a5b1fd2ae40dc19f543',
    messagingSenderId: '1041673028858',
    projectId: 'cbt-lpk',
    storageBucket: 'cbt-lpk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForIOS',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'cbt-mobile-app',
    storageBucket: 'cbt-mobile-app.appspot.com',
    iosBundleId: 'com.example.cbtMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForMacOS',
    appId: '1:123456789:macos:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'cbt-mobile-app',
    storageBucket: 'cbt-mobile-app.appspot.com',
    iosBundleId: 'com.example.cbtMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWindows',
    appId: '1:123456789:windows:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'cbt-mobile-app',
    storageBucket: 'cbt-mobile-app.appspot.com',
  );
}
